env:
  heroku: false
menu:
  font: Russo One
  theme: big_brother
  intro_text: "Select your nationality"
  outro_text: "By reading this you accept all terms and conditions of use"
categories:
  _defaults:
    font: Russo One
    theme: big_brother
    number_of_tweets: 12
    slide_wait_time: 8000
    slide_transition_time: 1000
    greeting_time: 2000
    chance_of_slogan: 5
    show_on_menu: true
  rig:
    title: RIG
    font: '' 
    theme: default
    show_on_menu: false
    greetings:
      - Ahoy!
      - Hello
    screen_names:
      - antimega
      - benterret
      - iotwatch
      - jamesbridle
      - philgyford
      - tomtaylor
      - undermanager
  us:
    title: United States
    screen_names:
      - barackobama
      - CDCemergency
      - deptofdefense
      - FBIPressOffice
      - FBIMostWanted
      - readygov
      - tsa
      - tsablogteam
      - usairforce
      - usarmy
      - uscis
      - usnavy
      - whitehouse
    burn_in_text: Yes we can
    greetings:
      - Attention<br>folks!
    slogans:
      - Believe in America
      - Country first
      - Forward
      - If you see something, say something
      - Stay the course
      - Yes we can
  uk:
    title: United Kingdom
    screen_names:
      - britisharmy
      - david_cameron
      - DefenceHQ
      - dwppressoffice
      - hmrcgovuk
      - mojgovuk
      - NCA_UK
      - number10gov
      - royalairforceuk
      - royalnavy
      - transportgovuk
      - ukhomeoffice
    burn_in_text: Go home<br>or<br>face arrest
    greetings:
      - Attention<br>subjects!
    slogans:
      - Are you thinking what we’re thinking?
      - You’ve had your debate
      - Go home or face arrest
      - Hardworking families

