menu:
  font: Russo One
  theme: big_brother
  intro_text: Select your nationality
  outro_text: By reading this you accept all terms and conditions of use
categories:
  _defaults:
    font: Russo One
    theme: big_brother
    number_of_tweets: 12
    slide_wait_time: 8000
    slide_transition_time: 1000
    greeting_time: 2000
    chance_of_slogan: 5
    show_on_menu: true
  fi:
    title: Finland
    screen_names:
      - alexstubb
      - AnneBerner
      - AnuVehvilainen
      - jniinisto
      - JuhaRehula
      - juhasipila
      - lindstrom_jari
      - ollirehn
      - p_orpo
      - sannigrahn
      - Tiilikainen
      - toivakka
      - DefenceFinland
      - FinGovernment
      - lvmfi
      - okmfi
      - Puolustusvoimat
      - Statsradet
      - STM_Uutiset
      - teamfinlandfi
      - TPkanslia
      - Ulkoministerio
      - Valtioneuvosto
      - VMuutiset
      - ymparisto
    burn_in_text: Think Finland
    greetings:
      - Tervetuloa<br>kansalaiset!
    slogans:
      - Connecting People
      - Visit Finland Breathe
      - FINNLAND. COOL.
      - Lend us your problems. We will solve them with interest.
  lt:
    title: Lithuania
    screen_names:
      - AButkevicius
      - Grybauskaite_LT
      - LRSeimas
      - Vyriausybe
      - LinkeviciusL
      - V_Andriukaitis
      - AndriusKubilius
      - MayorZuokas
      - liberalai
      - tslkd
      - RolandasPaksas
    burn_in_text: Drąsi Šalis
    greetings:
      - Dėmesio,<br>piliečiai!
    slogans:
      - Už Lietuvą, vyrai!
      - A country as ambitious as you are.
      - The center of Europe.
  us:
    title: United States
    screen_names:
      - barackobama
      - CDCemergency
      - deptofdefense
      - FBIPressOffice
      - FBIMostWanted
      - readygov
      - tsa
      - tsablogteam
      - usairforce
      - usarmy
      - uscis
      - usnavy
      - whitehouse
    burn_in_text: Yes we can
    greetings:
      - Attention<br>folks!
    slogans:
      - Believe in America
      - Country first
      - Forward
      - If you see something, say something
      - Stay the course
      - Yes we can
  uk:
    title: United Kingdom
    screen_names:
      - britisharmy
      - david_cameron
      - DefenceHQ
      - dwppressoffice
      - hmrcgovuk
      - mojgovuk
      - NCA_UK
      - number10gov
      - royalairforceuk
      - royalnavy
      - transportgovuk
      - ukhomeoffice
    burn_in_text: Go home<br>or<br>face arrest
    greetings:
      - Attention<br>subjects!
    slogans:
      - Are you thinking what we’re thinking?
      - You’ve had your debate
      - Go home or face arrest
      - Hardworking families
  rig:
    title: RIG
    font: '' 
    theme: default
    show_on_menu: false
    greetings:
      - Ahoy!
      - Hello
    screen_names:
      - antimega
      - benterret
      - iotwatch
      - jamesbridle
      - philgyford
      - tomtaylor
      - undermanager

